language: go

go:
  - 1.8
  - 1.9
  - 1.11
  - 1.12
  - master

sudo: enabled

before_install:
  - bash install-dependencies-ubuntu.sh
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
  - dep ensure

script:
  - go test -v -covermode=count -coverprofile=coverage.out -tags test
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
